version: '3.9'
services:
  node:
    image: node:18
    volumes:
      - type: bind
        source: $PWD
        target: /usr/src/app
    environment:
      - DB_NAME=inventory_dev
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_DRIVER=postgres

  inventory:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 50505:3000
    volumes:
      - type: bind
        source: $PWD/src
        target: /usr/src/app/src
      - type: bind
        source: $PWD/config
        target: /usr/src/app/config
    environment:
      - DB_NAME=inventory_dev
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_DRIVER=postgres
  postgres:
    image: 'postgres:14.3-alpine3.16'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: $PWD/config/postgresql.conf
        target: /etc/postgresql.conf
      - type: bind
        source: $PWD/config/pg_hba.conf
        target: /etc/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql.conf
